//Given two strings s and t which consist of only lowercase letters.

//String t is generated by random shuffling string s and then add one more letter at a random position.

//Find the letter that was added in t.

//Example:

//Input:
//s = "abcd"
//t = "abcde"

//Output:
//e

//Explanation:
//'e' is the letter that was added.

char findTheDifference(char* s, char* t) {
    int a,b,i;
    a=0,b=0,i=0;
    while(s[i])
    {
        a ^= s[i];
        b ^= t[i];
        i++;
    }
    return a^b^t[i];
}
